#!/bin/bash

# Run to push headers to rislab/c_library_v2
# Make sure this is already checked out in ${CLIBRARY_PATH}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# settings
VERSION=2
CLIBRARY_GIT_REMOTENAME=origin
CLIBRARY_GIT_BRANCHNAME=feature/upstream_merge
MAVLINK_PATH="$DIR/.."
CLIBRARY_PATH=$MAVLINK_PATH/include/mavlink/v$VERSION.0/c_library_v$VERSION

# save git hash
MAVLINK_GITHASH=$(git rev-parse HEAD)

# delete old c headers
rm -rf $CLIBRARY_PATH/*

# generate new c headers
echo -e "\0033[34mStarting to generate c headers\0033[0m\n"
python "${MAVLINK_PATH}/pymavlink/tools/mavgen.py" \
    --output $CLIBRARY_PATH \
    --lang C \
    --wire-protocol $VERSION.0 \
    "${MAVLINK_PATH}/message_definitions/v1.0/cmu_mavlink.xml"
mkdir -p $CLIBRARY_PATH/message_definitions
cp ${MAVLINK_PATH}/message_definitions/v1.0/* $CLIBRARY_PATH/message_definitions/.
echo -e "\0033[34mFinished generating c headers\0033[0m\n"

# git add and git commit in local c_library repository
cd "$CLIBRARY_PATH"
git add --all :/ || exit 1
COMMIT_MESSAGE="autogenerated RISLAB headers for rev https://github.com/rislab/mavlink/tree/"$MAVLINK_GITHASH
git commit -m "$COMMIT_MESSAGE" || exit 1

# push to c_library repository
git push $CLIBRARY_GIT_REMOTENAME $CLIBRARY_GIT_BRANCHNAME || exit 1
echo -e "\0033[34mHeaders updated and pushed successfully\0033[0m"
